// const data = [
//   {
//     foodName: "Butter Chicken",
//     timeTaken: "30 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.7,
//     mealType: "Non-Veg",
//     cuisine: "North Indian",
//     recipeId: "1111",
//     course: "Main Course",
//   },
//   {
//     foodName: "Paneer Tikka",
//     timeTaken: "25 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.6,
//     mealType: "Veg",
//     cuisine: "North Indian",
//     recipeId: "2222",
//     course: "Starter",
//   },
//   {
//     foodName: "Dal Makhani",
//     timeTaken: "40 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.8,
//     mealType: "Veg",
//     cuisine: "North Indian",
//     recipeId: "3333",
//     course: "Main Course",
//   },

//   {
//     foodName: "Chicken Tikka Masala",
//     timeTaken: "35 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.5,
//     mealType: "Non-Veg",
//     cuisine: "North Indian",
//     recipeId: "4444",
//     course: "Main Course",
//   },
//   {
//     foodName: "Margherita Pizza",
//     timeTaken: "20 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.6,
//     mealType: "Veg",
//     cuisine: "Italian",
//     recipeId: "5555",
//     course: "Main Course",
//   },
//   {
//     foodName: "Spaghetti Carbonara",
//     timeTaken: "25 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.4,
//     mealType: "Non-Veg",
//     cuisine: "Italian",
//     recipeId: "6666",
//     course: "Main Course",
//   },
//   {
//     foodName: "Tiramisu",
//     timeTaken: "40 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.9,
//     mealType: "Veg",
//     cuisine: "Italian",
//     recipeId: "7777",
//     course: "Dessert",
//   },
//   {
//     foodName: "Sushi",
//     timeTaken: "40 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.8,
//     mealType: "Non-Veg",
//     cuisine: "Japanese",
//     recipeId: "8888",
//     course: "Main Course",
//   },
//   {
//     foodName: "Ramen",
//     timeTaken: "35 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.7,
//     mealType: "Non-Veg",
//     cuisine: "Japanese",
//     recipeId: "9999",
//     course: "Main Course",
//   },
//   {
//     foodName: "Udon",
//     timeTaken: "30 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.6,
//     mealType: "Veg",
//     cuisine: "Japanese",
//     recipeId: "1010",
//     course: "Main Course",
//   },
//   {
//     foodName: "Mapo Tofu",
//     timeTaken: "35 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     mealType: "Veg",
//     cuisine: "Chinese",
//     recipeId: "1111",
//     course: "Main Course",
//   },
//   {
//     foodName: "Kung Pao Chicken",
//     timeTaken: "40 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.7,
//     mealType: "Non-Veg",
//     cuisine: "Chinese",
//     recipeId: "1212",
//     course: "Main Course",
//   },
//   {
//     foodName: "Peking Duck",
//     timeTaken: "60 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.8,
//     mealType: "Non-Veg",
//     cuisine: "Chinese",
//     recipeId: "1313",
//     course: "Main Course",
//   },
//   {
//     foodName: "Beef Wellington",
//     timeTaken: "60 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.9,
//     mealType: "Non-Veg",
//     cuisine: "Continental",
//     recipeId: "1414",
//     course: "Main Course",
//   },
//   {
//     foodName: "Caesar Salad",
//     timeTaken: "15 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.5,
//     mealType: "Veg",
//     cuisine: "Continental",
//     recipeId: "1515",
//     course: "Starter",
//   },
  //{
//     foodName: "Croissant",
//     timeTaken: "45 mins",
//     imageUrl: "https://via.placeholder.com/300",
//     rating: 4.6,
//     mealType: "Veg",
//     cuisine: "Continental",
//     recipeId: "1616",
//     course: "Main Course",
//   },
// ];

// export default data;
